### PR TITLE
Nested lists support

### LINKED ISSUE #8: Bugs in integration with undo
It's hard to find a TC, but errors happen. Couple of times I've seen `wrong-baseversion` messages., but I can't reproduce them now. I've also seen that:

screen shot 2016-09-28 at 15 33 38

This happens when you undo&redo some things. I managed to record this:

sep-28-2016 15-42-20

### LINKED ISSUE #9: Undo integration tests
There are no integration tests. Of course, as @scofalik said: 

> Theoretically, when undo works correctly you don't need tests.

But let's have them anyway :P.

### LINKED ISSUE #30: Coverage for the package dropped
https://codeclimate.com/github/ckeditor/ckeditor5-list/coverage

```
98.64%
```

!!! 💣

### LINKED ISSUE #36: List feature crashed browser tab
When monkey testing list feature (with undo) I managed to crash browser tab. It looked like infinite loop error. Unfortunately I wasn't able to reproduce it.

This issue is about making a research what could crash and why and, if the issue is found, fixing it.

The error probably happened during conversion. We use four loops in `converters.js`, but two of them are `for ... of` that ended surely. Other two are while loops:

1. First one is in `getSiblingListItem`: https://github.com/ckeditor/ckeditor5-list/blob/master/src/converters.js#L461-L471 . Unless somehow an element is added twice to the same parent, the loop has to end.

2. Second one is in `modelViewSplitOnInsert`: https://github.com/ckeditor/ckeditor5-list/blob/master/src/converters.js#L216-L225 . Once again, it looks like it should end: in worst case scenario, `viewPosition.parent` should finally be `null` and at least editor should throw an error.

### LINKED ISSUE #37: Undo with breaking list item before indented list item.
1. Open http://localhost:8125/ckeditor5-list/tests/manual/list.html
2. Indent third list item.
3. Go to second list item and break it (using enter key).
4. Use undo -> third list item disappears.
5. Use undo again -> error is thrown.

### LINKED ISSUE #38: Selection in empty list item that has a sublist
1. Open http://localhost:8125/ckeditor5-list/tests/manual/list.html
2. Remove text "Bullet list item 4"
3. Remove text "Bullet list item 3"
4. Indent the later empty bullet list item

image

You can put a selection in the upper empty list item, but trying to write in it or remove it will fail.

### LINKED ISSUE #39: Fixer for list feature.
List feature is a complicated one, because it needs some precise model structure. Some model states, connected with lists, are incorrect (even though they are correct with schema, etc.). For example, a list cannot start with indented element:

```xml
<listItem indent=2>Foo.</listItem>
<listItem indent=3>Bar.</listItem>
```

We "are able" to created such model structure even without writing any complicated code. For instance, we could wrap part of a list in another element, or copy+paste it.

For this reason, we need some kind of fixer for list feature, that would fix those wrong structures:

1. It would be fired with high priority on each `change` event.
2. If incorrect structure is noticed, it will change it -- probably without using `Batch` API - the change has to have an immediate impact and probably should not be seen by other features (undo, OT, etc.).

This issue is to discuss what kind of incorrect list feature model structure we may encounter and how the fixer should look like.

### LINKED ISSUE #40: Outdenting lists using enter key with indented lists
1. Open http://localhost:8125/ckeditor5-list/tests/manual/list.html
2. Indent item 5

Now you can break it:

1. Put caret at the end of item 4.
2. Press <kbd>Enter</kbd>.
3. Press <kbd>Enter</kbd> again.

Or:

1. Put caret at the end of item 5.
2. Press <kbd>Enter</kbd> three times.

Or:

1. Put caret at the end of item 6.
2. Press <kbd>Enter</kbd> two times.

Seems like something is wrong with mapping/model length evaluating with nested lists.

### LINKED ISSUE #41: Cannot convert nested lists from DOM to model.
Editor crashes and is empty when this is the editors starting content:

```html
<ul>
	<li>
		Bullet list item 1
		<ul>
			<li>Nested list item 1.1</li>
		</ul>
	</li>
	<li>Bullet list item 2</li>
</ul>
```

### LINKED ISSUE #44: Pasting a complex content throws an error
The minimal set of features is list+link.

I copied and pasted the entire content of https://github.com/SublimeText-Markdown/MarkdownEditing#configuration. I also saw the same error when pasting parts of http://gazeta.pl (although, be prepared that pasting some parts will totally freeze the browser – I'm not sure if it's a performance issue or some inf-loop because I was also experiencing freeze on CKEditor 4).

The error:

image

I also encountered different errors when typing pasting various content into the editor. They are often not reproducible when there's no list feature, so I'm afraid that most of the bugs come from here (together with the complexity of the feature of course).

I'd recommend doing a thorough check of pasting a content of some more complex websites to see how we're doing.

### LINKED ISSUE #45: Should it be possible to create two sublists in one item?
It's now possible to create such content:

image

```html
<ul>
  <li>
    abc
    <ul><li>abc</li></ul>
    <ol><li>abc</li></ol>
  </li>
  <li>abc</li>
</ul>
```

It's also possible to create such content in CKEditor 4. The process is the same way – just create a sub list with two items and convert one of them to a different type.

Fun fact – it makes CKEditor 4 very unstable (e.g. backspacing around these list items), so I guess it just wasn't anticipated.

CKEditor 5 is actually handling this quite well, but I'm not sure that this is the kind of a list that you should be able to achieve.

### LINKED ISSUE #2942: Undo integration tests
There are no integration tests. Of course, as @scofalik said: 

> Theoretically, when undo works correctly you don't need tests.

But let's have them anyway :P.

### LINKED ISSUE #2943: Bugs in integration with undo
It's hard to find a TC, but errors happen. Couple of times I've seen `wrong-baseversion` messages., but I can't reproduce them now. I've also seen that:

screen shot 2016-09-28 at 15 33 38

This happens when you undo&redo some things. I managed to record this:

sep-28-2016 15-42-20

### LINKED ISSUE #2959: Coverage for the package dropped
https://codeclimate.com/github/ckeditor/ckeditor5-list/coverage

```
98.64%
```

!!! 💣

### LINKED ISSUE #2962: Undo with breaking list item before indented list item.
1. Open http://localhost:8125/ckeditor5-list/tests/manual/list.html
2. Indent third list item.
3. Go to second list item and break it (using enter key).
4. Use undo -> third list item disappears.
5. Use undo again -> error is thrown.

### LINKED ISSUE #2963: List feature crashed browser tab
When monkey testing list feature (with undo) I managed to crash browser tab. It looked like infinite loop error. Unfortunately I wasn't able to reproduce it.

This issue is about making a research what could crash and why and, if the issue is found, fixing it.

The error probably happened during conversion. We use four loops in `converters.js`, but two of them are `for ... of` that ended surely. Other two are while loops:

1. First one is in `getSiblingListItem`: https://github.com/ckeditor/ckeditor5-list/blob/master/src/converters.js#L461-L471 . Unless somehow an element is added twice to the same parent, the loop has to end.

2. Second one is in `modelViewSplitOnInsert`: https://github.com/ckeditor/ckeditor5-list/blob/master/src/converters.js#L216-L225 . Once again, it looks like it should end: in worst case scenario, `viewPosition.parent` should finally be `null` and at least editor should throw an error.

### LINKED ISSUE #2964: Fixer for list feature.
List feature is a complicated one, because it needs some precise model structure. Some model states, connected with lists, are incorrect (even though they are correct with schema, etc.). For example, a list cannot start with indented element:

```xml
<listItem indent=2>Foo.</listItem>
<listItem indent=3>Bar.</listItem>
```

We "are able" to created such model structure even without writing any complicated code. For instance, we could wrap part of a list in another element, or copy+paste it.

For this reason, we need some kind of fixer for list feature, that would fix those wrong structures:

1. It would be fired with high priority on each `change` event.
2. If incorrect structure is noticed, it will change it -- probably without using `Batch` API - the change has to have an immediate impact and probably should not be seen by other features (undo, OT, etc.).

This issue is to discuss what kind of incorrect list feature model structure we may encounter and how the fixer should look like.

### LINKED ISSUE #2965: Selection in empty list item that has a sublist
1. Open http://localhost:8125/ckeditor5-list/tests/manual/list.html
2. Remove text "Bullet list item 4"
3. Remove text "Bullet list item 3"
4. Indent the later empty bullet list item

image

You can put a selection in the upper empty list item, but trying to write in it or remove it will fail.

### LINKED ISSUE #2966: Cannot convert nested lists from DOM to model.
Editor crashes and is empty when this is the editors starting content:

```html
<ul>
	<li>
		Bullet list item 1
		<ul>
			<li>Nested list item 1.1</li>
		</ul>
	</li>
	<li>Bullet list item 2</li>
</ul>
```

### LINKED ISSUE #2967: Outdenting lists using enter key with indented lists
1. Open http://localhost:8125/ckeditor5-list/tests/manual/list.html
2. Indent item 5

Now you can break it:

1. Put caret at the end of item 4.
2. Press <kbd>Enter</kbd>.
3. Press <kbd>Enter</kbd> again.

Or:

1. Put caret at the end of item 5.
2. Press <kbd>Enter</kbd> three times.

Or:

1. Put caret at the end of item 6.
2. Press <kbd>Enter</kbd> two times.

Seems like something is wrong with mapping/model length evaluating with nested lists.

### LINKED ISSUE #2968: Pasting a complex content throws an error
The minimal set of features is list+link.

I copied and pasted the entire content of https://github.com/SublimeText-Markdown/MarkdownEditing#configuration. I also saw the same error when pasting parts of http://gazeta.pl (although, be prepared that pasting some parts will totally freeze the browser – I'm not sure if it's a performance issue or some inf-loop because I was also experiencing freeze on CKEditor 4).

The error:

image

I also encountered different errors when typing pasting various content into the editor. They are often not reproducible when there's no list feature, so I'm afraid that most of the bugs come from here (together with the complexity of the feature of course).

I'd recommend doing a thorough check of pasting a content of some more complex websites to see how we're doing.

### PR DESCRIPTION
**Pull request by scofalik**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Feature: Nested lists support. Closes ckeditor/ckeditor5#2943. Closes ckeditor/ckeditor5#2942. Closes ckeditor/ckeditor5#2959. Closes ckeditor/ckeditor5#2963. Closes ckeditor/ckeditor5#2962. Closes ckeditor/ckeditor5#2965. Closes ckeditor/ckeditor5#2964. Closes ckeditor/ckeditor5#2967. Closes ckeditor/ckeditor5#2966. Closes ckeditor/ckeditor5#2968. Closes ckeditor/ckeditor5#2971.

### CODE REVIEW

**Comment by Reinmar** [comment]
I'm afraid some tests started failing after we closed https://github.com/ckeditor/ckeditor5-engine/pull/873. I restarted the build to check that it's not only my local problem.

I had a quick look at the code and... WOW. That's a test suite :) I checked that some lines of code are called 6-8k times ;)

**Comment by Reinmar** [comment]
Yep, some tests are failing now. And the old list tests were green on master according to https://travis-ci.org/ckeditor/ckeditor5/builds/212070784 so some of the new ones are failing.

**Comment by Reinmar** [comment]
I've also encountered this:

mar-18-2017 23-41-36

This behaviour I got on this branch. On list#master the behaviour was a bit different – the middle list item totally vanished on undo.

**Comment by scofalik** [comment]
It was difficult for me to test integration with non-existing feature ;).

As far as failing tests are concerned, all of them are for move change. I'll check it, it's probably connected with the recent changes we did to move conversion.

**Comment by scofalik** [comment]
Fixes #44.

**Comment by Reinmar** [comment]
mar-20-2017 19-54-44

Is this one of these ignored cases?

**Comment by Reinmar** [comment]
One more broken thing – select multiple items and press <kbd>Tab</kbd>. Only the first of the selected items get indented.

Other than that... I've been able to achieve some "out of bounds index" errors couple of times, but I'm not able to repeat any of these scenarios. It happened in the nested lists manual test which contains that odd data (see https://github.com/ckeditor/ckeditor5-list/issues/45) and I haven't seen any bug if those items weren't present somewhere, so perhaps it doesn't make sense to try to investigate this further at the moment.

EDIT, it happened once on paste (from gazeta.pl) and selection move. Maybe this screenshot will help you somehow:

image


So, this is really impressive how this feature works. It's the first version and you really need to push it hard to get some errors :). Believe me – this is a really big achievement 🥇

**Comment by scofalik** [comment]
The bug with empty list is very sad, as it was working for most part of the time. One of the most recent commits must had broken it.

Indenting just one item is a feature, actually :P. I mean it was designed to work like this. I don't know what I based it on, but if it looks like it's broken, then it needs to be fixed.

As far as the error is concerned, you are right that it looks like something with selection. It's a pity that you haven't saved other error messages. Is there a possibility that the editor threw on undo/redo? Restoring selection is quite unstable ATM and might throw such errors (when model range is incorrectly restored and is then mapped to view).

> It's the first version and you really need to push it hard to get some errors :).

It's kinda second version but I appreciate that you try to keep my morale up :P

**Comment by scofalik** [comment]
The bug with empty list is caused by imperfect model-to-view position mapping and the recent change in model-to-view remove converter (using `viewPosition` instead of element mapping to get `viewItem` to remove). I'll see what can be done on this matter.

**Comment by scofalik** [comment]
Upon further research it appears that model-to-view position is ... heavily flawed. I haven't noticed it because it appeared that almost nothing in conversion uses model-to-view position mapping -- converters tried to use element mapping whenever is needed. Now we used position mapping in remove converter and actually a lot of cases are falling. I'll look at unit tests too.

I am not sure whether it will be possible to fix it considering how `Mapper` works now, so we may need to do some bigger changes in `Mapper`.

**Comment by fredck** [comment]
> Indenting just one item is a feature, actually :P. I mean it was designed to work like this. I don't know what I based it on, but if it looks like it's broken, then it needs to be fixed.

I think it needs to be fixed.

**Comment by scofalik** [comment]
I've pushed a commit but it fails because it needs https://github.com/ckeditor/ckeditor5-engine/pull/885 .

The commit handles position mapping. I also expanded the position mapping test. This bug is fixed:

mar-20-2017 19-54-44

**Comment by scofalik** [comment]
Added indenting/outdenting of multiple items at once.

**Comment by scofalik** [comment]
Fixed #45.

**Comment by Reinmar** [comment]
I found one quite important issue: https://github.com/ckeditor/ckeditor5-list/issues/51 and a scenario which I guess may throw at some point – https://github.com/ckeditor/ckeditor5-list/issues/48#issuecomment-289065138. Other than that, all worked fine.

**Pull request merged**
