### PR TITLE
Editor was crashing if multiple, specific block elements were inside list item in loaded/pasted data

### PR DESCRIPTION
**Pull request by scofalik**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: Editor was crashing if multiple, specific block elements were inside list item in loaded/pasted data. Closes https://github.com/ckeditor/ckeditor5/issues/1572.

### CODE REVIEW

**Comment by scofalik** [comment]
https://github.com/ckeditor/ckeditor5-paragraph/issues/43 This may be an alternative solution to the problem

**Comment by scofalik** [comment]
Maybe I will elaborate more on it: if we would fix autoparagraphing, maybe we don't need to change lists at all. But OTOH we cannot guarantee that every converter will set `modelCursor` correctly. So proposed solution is still a little safer than relying on `modelCursor`.

**Comment by Mgsy** [comment]
I've spent some time pasting different content, including multiple blocks in a list item, and it looks good to me.

**Review by Reinmar — APPROVED** [review]
The code looks good. It works fine as well. I was not able to crash the editor except by doing something when an image is selected in case of very long content (https://github.com/ckeditor/ckeditor5/issues/1578).

**Pull request merged**
