### PR TITLE
Docs for to-do list feature

### PR DESCRIPTION
**Pull request by pjasiun**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Docs: Docs for to-do list feature. Part of https://github.com/ckeditor/ckeditor5/issues/1434.

---

### Additional information

Docs need to be updated when the feature will be ready:
 - links to the API need to be added,
 - live demo need to be updated.

### CODE REVIEW

**Comment by Reinmar** [comment]
Just to be sure – what's the source of that waffles image and what's its license?

**Comment by pjasiun** [comment]
It was taken from the free images stock (https://www.pexels.com/search/waffles/) and it is free to use (https://www.pexels.com/photo-license/).

**Comment by Reinmar** [comment]
I started wondering – should we have a separate guide for the list feature?

If yes, then there will be a "Lists" position in the left menu. Should the todo list feature guide be merged into it? Or should it be kept separately?

**Comment by Reinmar** [comment]
> If yes, then there will be a "Lists" position in the left menu. Should the todo list feature guide be merged into it? Or should it be kept separately?

Actually, I wanted to answer this myself  – I'd keep it separately becasue while normal lists are part of all builds, this feature will not be. Also, it's quite "special" and it's better to increase its visibility by extracting it to a separate guide.

This means that we don't need to work now on a generic "Lists" feature guide, because it will be completely separate from the currently proposed "To-do lists" guide.

**Comment by Reinmar** [comment]
The PR LGTM. I'll merge it but once the implementation of the feature lands we'll have to do some minor tweaks like:

* Link to TodoList plugin whenever the class is mentioned.
* Add "Common API" section (as in other guides).

**Comment by pjasiun** [comment]
I think we should have a separate list feature guide. But I also think it should be separate. I believe that from the end-user perspective these are two separate features. Todo lists do not make sense in many cases (for instance document editor). Also, when you think about use cases for to-do lists, they are different than use cases for lists.

**Pull request merged**
