### PR TITLE
List feature patches.

### LINKED ISSUE #49: ListCommand and IndentCommand should not listen on sel#change:range
It's enough to listen on `changesDone`.

Note: Some tests will fail – they fail due to changing the selection without enqChanges.

### LINKED ISSUE #52: List item can be moved to previous list when you indent it
It shouldn't be possible to indent an item which starts a list, but it is possible if it follows a different list:

mar-24-2017 17-17-22

### LINKED ISSUE #57: Indenting should fix the list type too
mar-29-2017 11-13-01

### LINKED ISSUE #2975: ListCommand and IndentCommand should not listen on sel#change:range
It's enough to listen on `changesDone`.

Note: Some tests will fail – they fail due to changing the selection without enqChanges.

### LINKED ISSUE #2977: List item can be moved to previous list when you indent it
It shouldn't be possible to indent an item which starts a list, but it is possible if it follows a different list:

mar-24-2017 17-17-22

### LINKED ISSUE #2980: Indenting should fix the list type too
mar-29-2017 11-13-01

### PR DESCRIPTION
**Pull request by scofalik**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: Improvements to List feature:
* commands listen only to `model.Document#event:changesDone`,
* list item type fixing when item is indented/outdented is improved,
* removed possibility to indent first list item of a list, if that list was top level list of different type.

Closes ckeditor/ckeditor5#2975. Closes ckeditor/ckeditor5#2977. Closes ckeditor/ckeditor5#2980.

### CODE REVIEW

**Comment by Reinmar** [comment]
I can see only one new test and at two points regarding changes in how indent/outdent work. So... where is all this verified? ;)

**Comment by scofalik** [comment]
I have added more tests.

**Comment by Reinmar** [comment]
1. Open http://localhost:8125/ckeditor5-list/tests/manual/nestedlists.html
2. Place caret in: 
    image
3. Press <kbd>Tab</kbd>.

Type of the nested list changed (as not expected), but nothing more happened (as expect).

**Comment by scofalik** [comment]
I fixed the bug (the origin of it was in `_checkEnabled`, actually). I also introduced even more improvements to `IndentCommand`, as I found one more bug (with outdenting).

There are multiple new tests, because I run into those scenarios when fixing the bug I found (I kept all new tests even though they were working without the fixes, but at some point they crashed so I think it's good to keep them).

**Comment by scofalik** [comment]
@Reinmar found two more bugs (these are regressions):

Last item can be indented:
pasted image at 2017_03_30 12_52
Items type is not corrected:
mar-30-2017 12-53-53

**Comment by scofalik** [comment]
Aaaaand they're gone!

**Pull request merged**
