### PR TITLE
Use model.Selection#getSelectedBlocks() instead of private logic

### LINKED ISSUE #31: Commands aren't disabled when in disallowed context
1. Open https://ckeditor5.github.io
2. Focus the image.
3. The list buttons should be disabled, but they are not.

### LINKED ISSUE #32: Start using Selection#getSelectedBlocks()
The method will be introduced in https://github.com/ckeditor/ckeditor5-engine/issues/811.

### LINKED ISSUE #2958: Commands aren't disabled when in disallowed context
1. Open https://ckeditor5.github.io
2. Focus the image.
3. The list buttons should be disabled, but they are not.

### LINKED ISSUE #2960: Start using Selection#getSelectedBlocks()
The method will be introduced in https://github.com/ckeditor/ckeditor5-engine/issues/811.

### PR DESCRIPTION
**Pull request by Reinmar**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Other: Made the list feature use the `model.Selection#getSelectedBlocks()` instead of implementing the same logic itself. Closes ckeditor/ckeditor5#2960. Closes ckeditor/ckeditor5#2958.

---

### Additional information

Requires https://github.com/ckeditor/ckeditor5-engine/pull/817.

When removing the `getPositionBeforeBlock()` function I noticed that the tests for command's `isEnabled` state were unrealistic and the implementation was unnecessarily complicated. I decided to reuse the `getSelectedBlocks()` logic and hopefully fixed also ckeditor/ckeditor5#2958.

### CODE REVIEW

**Comment by Reinmar** [comment]
Yep, it fixes #31:

feb-13-2017 15-56-01

**Comment by scofalik** [comment]
It looks fine. I've checked manual test for lists do see if something does not break. It's ok. I also checked whether it fixes #31 and it does.

**Comment by scofalik** [comment]
Unfortunately somewhere we've lost 100%CC for this repo. However it's not because of this PR. I will make an issue about it.

**Comment by scofalik** [comment]
I see there is already an issue about this #30

**Comment by Reinmar** [comment]
Yes, there is ;>

**Pull request merged**
